### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/api/reviews
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="review"
Content-Type: application/json

{
  "userId": 1,
  "title": "d",
  "nickname": "d",
  "content": "굿보이!"
}

###
GET http://localhost:8080/api/reviews

###
GET http://localhost:8080/api/reviews/8

###
PUT http://localhost:8080/api/reviews/8
Content-Type: application/json
Accept: application/json

{
  "title": "ddd",
  "content": "수정된 리뷰 내용입니다!"
}


###
DELETE http://localhost:8080/api/contacts/1